version: '3.9'

services:
  db:
    image: postgis/postgis:13-3.1
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'noiseworks'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: /app/script/server --development
    volumes:
      - .:/app
      - node_modules:/app/cobrand_hackney/node_modules/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    environment:
      SECRET_KEY: 'secret'
      DEBUG: 1
      DATABASE_URL: 'postgis://postgres:password@db/noiseworks'
      COBRAND: cobrand_hackney
      EMAIL_HOST: email.svc
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
     default:
       aliases:
         - email.svc

volumes:
  pgdata:
  node_modules:
