# Generated by Django 3.2.3 on 2021-07-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_action_actiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='uprn_cache',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
