# Generated by Django 3.2.3 on 2021-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_complaint_complainant'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ward',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
