# Generated by Django 3.2.3 on 2021-09-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='estate',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('?', 'Don’t know')], max_length=1),
        ),
    ]
