# Generated by Django 3.2.3 on 2021-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='kind',
            field=models.CharField(choices=[('car', 'Car alarm'), ('diy', 'DIY'), ('dog', 'Dog barking'), ('alarm', 'House / intruder alarm'), ('music', 'Music'), ('road', 'Noise on the road'), ('shouting', 'Shouting'), ('tv', 'TV'), ('other', 'Other')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kind_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other type'),
        ),
    ]
