# Generated by Django 3.2.3 on 2021-11-01 13:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_actiontype_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=27700),
        ),
    ]
