# Generated by Django 3.2.3 on 2021-11-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20211101_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='case',
            name='longitude',
        ),
    ]
