# Generated by Django 3.2.3 on 2021-11-11 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_rename_uprn_cache_case_location_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='happening_days',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='happening_description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='happening_pattern',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='happening_times',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='more_details',
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='effect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rooms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
