# Generated by Django 3.2.3 on 2021-11-04 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0013_rename_uprn_cache_case_location_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='perpetrators',
            field=models.ManyToManyField(related_name='cases_perpetrated', to=settings.AUTH_USER_MODEL),
        ),
    ]
