# Generated by Django 3.2.3 on 2021-11-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20211111_1050'),
        ('cases', '0014_case_perpetrators'),
    ]

    operations = [
    ]
