# Generated by Django 3.2.9 on 2021-11-25 15:00

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0015_merge_0014_auto_20211111_1050_0014_case_perpetrators'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('kind', models.CharField(choices=[('car', 'Car alarm'), ('diy', 'DIY'), ('dog', 'Dog barking'), ('alarm', 'House / intruder alarm'), ('music', 'Music'), ('road', 'Noise on the road'), ('shouting', 'Shouting'), ('tv', 'TV'), ('other', 'Other')], max_length=10, verbose_name='Type')),
                ('kind_other', models.CharField(blank=True, max_length=100, verbose_name='Other type')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=27700)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('uprn', models.CharField(blank=True, max_length=20)),
                ('location_cache', models.CharField(blank=True, max_length=200)),
                ('ward', models.CharField(blank=True, max_length=9)),
                ('where', models.CharField(choices=[('business', 'A shop, bar, nightclub, building site or other commercial premises'), ('residence', 'A house, flat, park or street')], max_length=9)),
                ('estate', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('?', 'Don’t know')], max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical case',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
