# Generated by Django 3.2.9 on 2021-11-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_historicalcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='assigned_new',
        ),
        migrations.RemoveField(
            model_name='action',
            name='assigned_old',
        ),
    ]
