# Generated by Django 3.2.3 on 2021-11-22 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0017_auto_20211125_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='followers',
            field=models.ManyToManyField(related_name='cases_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
