# Generated by Django 3.2.11 on 2022-02-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20220119_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('-modified', '-id')},
        ),
    ]
