# Generated by Django 3.2.12 on 2022-03-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_case_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='kind',
            field=models.CharField(choices=[('animal', 'Animal noise'), ('buskers', 'Buskers'), ('car', 'Car alarm'), ('construction', 'Construction site noise'), ('deliveries', 'Deliveries'), ('diy', 'DIY'), ('alarm', 'House / intruder alarm'), ('music-pub', 'Music from pub'), ('music-club', 'Music from club/bar'), ('music-other', 'Music - other'), ('festival', 'Noise caused by Religious Festivals'), ('roadworks', 'Noise from roadworks'), ('road', 'Noise on the road'), ('plant-machinery', 'Plant noise - machinery'), ('plant-street', 'Plant noise - machinery on street'), ('shouting', 'Shouting'), ('tv', 'TV'), ('other', 'Other')], max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='kind',
            field=models.CharField(choices=[('animal', 'Animal noise'), ('buskers', 'Buskers'), ('car', 'Car alarm'), ('construction', 'Construction site noise'), ('deliveries', 'Deliveries'), ('diy', 'DIY'), ('alarm', 'House / intruder alarm'), ('music-pub', 'Music from pub'), ('music-club', 'Music from club/bar'), ('music-other', 'Music - other'), ('festival', 'Noise caused by Religious Festivals'), ('roadworks', 'Noise from roadworks'), ('road', 'Noise on the road'), ('plant-machinery', 'Plant noise - machinery'), ('plant-street', 'Plant noise - machinery on street'), ('shouting', 'Shouting'), ('tv', 'TV'), ('other', 'Other')], max_length=15, verbose_name='Type'),
        ),
    ]
