# Generated by Django 3.2.15 on 2022-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20220304_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcase',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical case', 'verbose_name_plural': 'historical cases'},
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
