# Generated by Django 3.2.15 on 2022-08-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20220809_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
