# Generated by Django 3.2.15 on 2022-08-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20220809_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcase',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='modified_by',
        ),
    ]
