# Generated by Django 3.2.15 on 2022-08-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_auto_20220818_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='case_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_action', to='cases.case'),
        ),
    ]
