# Generated by Django 3.2.15 on 2022-09-05 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_action_case_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
