# Generated by Django 3.2.15 on 2022-09-05 12:43
# Empty migration filled in manually.

from django.db import migrations
from django.db.models import F

def forwards_func(apps, schema_editor):
    Action = apps.get_model('cases', 'Action')
    Action.objects.update(time=F('created'))

def reverse_func(apps, schema_editor):
    # We shouldn't need to undo this change.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_action_time'),
    ]

    operations = [
            migrations.RunPython(forwards_func, reverse_func)
    ]
