# Generated by Django 3.2.15 on 2022-09-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_populate_action_time_from_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('-created', '-id')},
        ),
    ]
