# Generated by Django 3.2.15 on 2022-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_populate_action_time_from_created_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['time'], name='cases_actio_time_278131_idx'),
        ),
    ]
