# Generated by Django 3.2.15 on 2022-10-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_set_initial_case_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
