# Generated by Django 3.2.15 on 2022-10-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_auto_20221011_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
