# Generated by Django 3.2.15 on 2022-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_auto_20221012_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='last_update_type',
            field=models.CharField(blank=True, choices=[('AC', 'Action'), ('CO', 'Complaint')], max_length=2),
        ),
    ]
