# Generated by Django 3.2.15 on 2022-10-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0033_populate_case_last_update_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mergees', to='cases.case'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='merged_into',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case'),
        ),
    ]
