# Generated by Django 3.2.15 on 2022-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_actionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesettingssingleton',
            name='max_file_storage_mb',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
