# Generated by Django 3.2.15 on 2022-10-18 15:43
# Empty migration filled in manually.

from django.db import migrations


def forwards_func(apps, schema_editor):
    Action = apps.get_model("cases", "Action")
    MergeRecord = apps.get_model("cases", "MergeRecord")
    actions = Action.objects.filter(case_old__isnull=False)
    for action in actions:
        MergeRecord.objects.create(
            mergee_id=action.case_old_id,
            merged_into_id=action.case_id,
            time=action.time,
            created_by_id=action.created_by_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0036_mergerecord"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
