# Generated by Django 3.2.15 on 2022-10-17 13:49
# Empty migration filled in manually.

from django.db import migrations


def forwards_func(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    cases = Case.objects.prefetch_related("merge_action")

    # Set 'merged_into' based on the most recent
    # merging action on the case.
    for case in cases:
        for action in case.merge_action.all():
            case.merged_into_id = action.case_id
            case.save()
            break


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0036_auto_20221101_1541"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
