# Generated by Django 3.2.15 on 2022-10-24 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0037_populate_merged_into'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('unmerge', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mergerecord_set', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergee_records', to='cases.case')),
                ('mergee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_records', to='cases.case')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_mergerecord_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
