# Generated by Django 3.2.15 on 2022-10-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_populate_merge_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update_type',
            field=models.CharField(blank=True, choices=[('AC', 'Action'), ('CO', 'Complaint'), ('MR', 'Merge')], max_length=2),
        ),
    ]
