# Generated by Django 3.2.15 on 2022-11-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0043_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('-modified', '-id'), 'permissions': [('edit_perpetrators', 'Can add and remove perpetrators and edit their details'), ('follow', 'Can follow a case'), ('get_assigned', 'Can get assigned to a case'), ('assign', 'Can assign a case'), ('change_priority', 'Can change priority'), ('change_review_date', 'Can change review date'), ('merge', 'Can merge and unmerge cases')]},
        ),
    ]
