# Generated by Django 3.2.15 on 2022-11-07 12:06
# Empty migration filled in manually.

from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Group = apps.get_model("auth", "Group")
    case_workers = Group.objects.get(name="case_workers")
    staff = User.objects.filter(is_staff=True).all()
    case_workers.user_set.add(*staff)


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0045_add_case_worker_group"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
