# Generated by Django 3.2.15 on 2022-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0046_make_all_staff_case_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='notes_last_edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
