# Generated by Django 4.2.30 on 2026-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0048_alter_action_created_by_alter_action_modified_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="kind",
            field=models.CharField(max_length=15, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="historicalcase",
            name="kind",
            field=models.CharField(max_length=15, verbose_name="Type"),
        ),
    ]
