# Generated by Django 4.2.30 on 2026-10-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0049_alter_case_kind_alter_historicalcase_kind"),
        ("cases", "0049_complaintfile"),
    ]

    operations = []
