# Generated by Django 3.2.3 on 2021-07-08 17:13

import accounts.models
import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='best_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='best_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('weekday', 'Weekdays'), ('weekend', 'Weekends'), ('evening', 'Evenings')], max_length=7), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='uprn',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
