# Generated by Django 3.2.3 on 2021-08-24 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210708_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), blank=True, null=True, size=None),
        ),
    ]
