# Generated by Django 3.2.15 on 2022-09-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220117_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estate',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('?', 'Don’t know')], max_length=1),
        ),
    ]
