# Generated by Django 3.2.15 on 2022-11-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_warning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
