# Generated by Django 3.2.15 on 2022-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_web_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
