# Generated by Django 3.2.15 on 2023-01-26 17:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20221215_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='principal_wards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9), default=list, size=None),
        ),
    ]
