#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

# This should contain commmands to reset the environment to a default state.
# Some possible examples:
# rm .env
# (cd cobrand_hackney && rm -fr node_modules)

# Run the update script
./script/update
