#!/bin/bash

# abort on any errors
set -e

# check that we are in the expected directory
cd `dirname $0`/..

(cd cobrand_hackney && npm install)
poetry install --no-root
poetry run python manage.py migrate
